---
- hosts: all
  name: Scale deploymentconfig playbook

  tasks:
    - name: Log in (obtain access token)
      k8s_auth:
        username: "{{ k8s_user }}"
        password: "{{ k8s_password }}"
        host: "{{ k8s_host }}"
        validate_certs: no
      register: k8s_auth_results

    - name: remove deployment
      k8s:
        api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
        api_version: apps.openshift.io/v1
        kind: deploymentconfig
        state: absent
        name: "{{ dc_name }}"
        namespace: "{{ dc_ns }}"
